### ISSUE TITLE
Publish errors on prod

### ISSUE THREAD

**Issue by humphd** [mozilla/publish.webmaker.org#144]
I've seen a few of these fly by on Heroku logs for publish on prod:

```
 Sep 03 14:23:59 publish-webmaker-org-prod app/web.4: [2015-09-03T21:23:59.081Z] ERROR: publish.webmaker.org/3 on f9d50455-96f5-4bac-9ea1-770e58f85493: Not Found 
Sep 03 14:23:59 publish-webmaker-org-prod app/web.4:     Error: Not Found 
Sep 03 14:23:59 publish-webmaker-org-prod app/web.4:         at Object.exports.create (/app/node_modules/boom/lib/index.js:21:17) 
Sep 03 14:23:59 publish-webmaker-org-prod app/web.4:         at Object.exports.notFound (/app/node_modules/boom/lib/index.js:165:20) 
Sep 03 14:23:59 publish-webmaker-org-prod app/web.4:         at null.<anonymous> (/app/api/classes/prerequisites.js:50:50) 
Sep 03 14:23:59 publish-webmaker-org-prod app/web.4:         at bound (domain.js:254:14) 
Sep 03 14:23:59 publish-webmaker-org-prod app/web.4:         at runBound (domain.js:267:12) 
Sep 03 14:23:59 publish-webmaker-org-prod app/web.4:         at tryCatcher (/app/node_modules/bluebird/js/main/util.js:26:23) 
Sep 03 14:23:59 publish-webmaker-org-prod app/web.4:         at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/main/promise.js:503:31) 
Sep 03 14:23:59 publish-webmaker-org-prod app/web.4:         at Promise._settlePromiseAt (/app/node_modules/bluebird/js/main/promise.js:577:18) 
Sep 03 14:23:59 publish-webmaker-org-prod app/web.4:         at Async._drainQueue (/app/node_modules/bluebird/js/main/async.js:128:12) 
Sep 03 14:23:59 publish-webmaker-org-prod app/web.4:         at Async._drainQueues (/app/node_modules/bluebird/js/main/async.js:133:10) 
Sep 03 14:23:59 publish-webmaker-org-prod app/web.4:         at Immediate.Async.drainQueues [as _onImmediate] (/app/node_modules/bluebird/js/main/async.js:15:14) 
Sep 03 14:23:59 publish-webmaker-org-prod app/web.4:         at processImmediate [as _immediateCallback] (timers.js:367:17) 
Sep 03 14:23:59 publish-webmaker-org-prod app/web.4: [2015-09-03T21:23:59.082Z] ERROR: publish.webmaker.org/3 on f9d50455-96f5-4bac-9ea1-770e58f85493:  
Sep 03 14:23:59 publish-webmaker-org-prod app/web.4:      
Sep 03 14:23:59 publish-webmaker-org-prod app/web.4:     -- 
Sep 03 14:23:59 publish-webmaker-org-prod app/web.4:     req_id: 1441315438917:f9d50455-96f5-4bac-9ea1-770e58f85493:3:ie4i7l04:16023 
Sep 03 14:23:59 publish-webmaker-org-prod app/web.4:     -- 
Sep 03 14:23:59 publish-webmaker-org-prod app/web.4:     data: { 
Sep 03 14:23:59 publish-webmaker-org-prod app/web.4:       "msec": 53.303678035736084, 
Sep 03 14:23:59 publish-webmaker-org-prod app/web.4:       "assign": "records", 
Sep 03 14:23:59 publish-webmaker-org-prod app/web.4:       "error": { 
Sep 03 14:23:59 publish-webmaker-org-prod app/web.4:         "data": null, 
Sep 03 14:23:59 publish-webmaker-org-prod app/web.4:         "isBoom": true, 
Sep 03 14:23:59 publish-webmaker-org-prod app/web.4:         "isServer": false, 
Sep 03 14:23:59 publish-webmaker-org-prod app/web.4:         "output": { 
Sep 03 14:23:59 publish-webmaker-org-prod app/web.4:           "statusCode": 404, 
Sep 03 14:23:59 publish-webmaker-org-prod app/web.4:           "payload": { 
Sep 03 14:23:59 publish-webmaker-org-prod app/web.4:             "statusCode": 404, 
Sep 03 14:23:59 publish-webmaker-org-prod app/web.4:             "error": "Not Found" 
Sep 03 14:23:59 publish-webmaker-org-prod app/web.4:           }, 
Sep 03 14:23:59 publish-webmaker-org-prod app/web.4:           "headers": {} 
Sep 03 14:23:59 publish-webmaker-org-prod app/web.4:         }, 
Sep 03 14:23:59 publish-webmaker-org-prod app/web.4:         "message": "Not Found" 
Sep 03 14:23:59 publish-webmaker-org-prod app/web.4:       } 
Sep 03 14:23:59 publish-webmaker-org-prod app/web.4:     }
```

Not sure how much of a problem it is, but doesn't look like a normal thing to be spitting out.

cc @ashleygwilliams, @gideonthomas

**Comment by sedge** [comment]
This probably isn't a big deal IMO. The Thimble server queries the Publish server for resources in predictable situations, like creating a user and in some of these a valid response would be "it doesn't exist". With [better logging](https://github.com/mozilla/publish.webmaker.org/issues/143) we'll know for sure.

**Comment by gideonthomas** [comment]
@sedge we think this might be related to https://github.com/mozilla/thimble.webmaker.org/issues/1040 because we also see publish uploads happening twice for some files to S3; i.e. if I have `index.html`, `style.css`, `script.js`, `a.txt` files in my project, we sometimes see, for e.g. `index.html` and `style.css` being uploaded twice to S3. Meaning somehow we have two copies or something.
But as you said, it is worth investigating with better logging!

**Comment by sedge** [comment]
Until there are better logs this can't really move forward.
