### ISSUE TITLE
Docs probably need an update

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/publish.webmaker.org#182]
I can no longer just run `npm run knex` anymore.

Before, I could run `npm run knex` more than once and it would work fine.
Now, if I run it more than once, I get:
```
> knex seed:run

Using environment: development
Ran 3 seed files
/Users/gideonthomas/publish.webmaker.org/seeds/1_users.js
/Users/gideonthomas/publish.webmaker.org/seeds/2_projects.js
/Users/gideonthomas/publish.webmaker.org/seeds/3_files.js
➜  publish.webmaker.org git:(master) gst
On branch master
Your branch is up-to-date with 'upstream/master'.
nothing to commit, working directory clean
➜  publish.webmaker.org git:(master) npm run knex

> publish.webmaker.org@0.0.1 knex /Users/gideonthomas/publish.webmaker.org
> npm run migrate && npm run seed


> publish.webmaker.org@0.0.1 migrate /Users/gideonthomas/publish.webmaker.org
> knex migrate:latest

Using environment: development
Already up to date

> publish.webmaker.org@0.0.1 seed /Users/gideonthomas/publish.webmaker.org
> knex seed:run

Using environment: development
error: duplicate key value violates unique constraint "users_name_unique"
    at Connection.parseE (/Users/gideonthomas/publish.webmaker.org/node_modules/pg/lib/connection.js:539:11)
    at Connection.parseMessage (/Users/gideonthomas/publish.webmaker.org/node_modules/pg/lib/connection.js:366:17)
    at Socket.<anonymous> (/Users/gideonthomas/publish.webmaker.org/node_modules/pg/lib/connection.js:105:22)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
From previous event:
    at Client._query (/Users/gideonthomas/publish.webmaker.org/node_modules/knex/lib/dialects/postgres/index.js:122:12)
    at Client.query (/Users/gideonthomas/publish.webmaker.org/node_modules/knex/lib/client.js:127:24)
    at Runner.<anonymous> (/Users/gideonthomas/publish.webmaker.org/node_modules/knex/lib/runner.js:118:24)
From previous event:
    at /Users/gideonthomas/publish.webmaker.org/node_modules/knex/lib/runner.js:44:21
From previous event:
    at Runner.run (/Users/gideonthomas/publish.webmaker.org/node_modules/knex/lib/runner.js:30:20)
    at QueryBuilder.Target.then (/Users/gideonthomas/publish.webmaker.org/node_modules/knex/lib/interface.js:27:43)
    at Object.exports.seed (/Users/gideonthomas/publish.webmaker.org/seeds/1_users.js:4:18)
    at Object.<anonymous> (/Users/gideonthomas/publish.webmaker.org/node_modules/knex/lib/seed/index.js:110:19)
From previous event:
    at /Users/gideonthomas/publish.webmaker.org/node_modules/knex/lib/seed/index.js:109:23
    at arrayEach (/Users/gideonthomas/publish.webmaker.org/node_modules/knex/node_modules/lodash/index.js:1314:13)
    at Function.<anonymous> (/Users/gideonthomas/publish.webmaker.org/node_modules/knex/node_modules/lodash/index.js:3355:13)
    at Seeder._waterfallBatch (/Users/gideonthomas/publish.webmaker.org/node_modules/knex/lib/seed/index.js:104:5)
    at Seeder.<anonymous> (/Users/gideonthomas/publish.webmaker.org/node_modules/knex/lib/seed/index.js:64:19)
From previous event:
    at Seeder.<anonymous> (/Users/gideonthomas/publish.webmaker.org/node_modules/knex/lib/seed/index.js:63:31)
From previous event:
    at Seeder._runSeeds (/Users/gideonthomas/publish.webmaker.org/node_modules/knex/lib/seed/index.js:62:82)
    at Seeder.<anonymous> (/Users/gideonthomas/publish.webmaker.org/node_modules/knex/lib/seed/index.js:24:17)
    at processImmediate [as _immediateCallback] (timers.js:374:17)
From previous event:
    at Seeder.<anonymous> (/Users/gideonthomas/publish.webmaker.org/node_modules/knex/lib/seed/index.js:23:38)
From previous event:
    at Command.<anonymous> (/Users/gideonthomas/publish.webmaker.org/node_modules/knex/lib/bin/cli.js:134:34)
    at Command.listener (/Users/gideonthomas/publish.webmaker.org/node_modules/knex/node_modules/commander/index.js:301:8)
    at emitTwo (events.js:87:13)
    at Command.emit (events.js:172:7)
    at Command.parseArgs (/Users/gideonthomas/publish.webmaker.org/node_modules/knex/node_modules/commander/index.js:610:12)
    at Command.parse (/Users/gideonthomas/publish.webmaker.org/node_modules/knex/node_modules/commander/index.js:458:21)
    at Liftoff.invoke (/Users/gideonthomas/publish.webmaker.org/node_modules/knex/lib/bin/cli.js:142:13)
    at Liftoff.<anonymous> (/Users/gideonthomas/publish.webmaker.org/node_modules/knex/node_modules/liftoff/index.js:181:16)
    at module.exports (/Users/gideonthomas/publish.webmaker.org/node_modules/knex/node_modules/liftoff/node_modules/flagged-respawn/index.js:17:3)
    at Liftoff.<anonymous> (/Users/gideonthomas/publish.webmaker.org/node_modules/knex/node_modules/liftoff/index.js:174:9)
    at /Users/gideonthomas/publish.webmaker.org/node_modules/knex/node_modules/liftoff/index.js:148:9
    at /Users/gideonthomas/publish.webmaker.org/node_modules/knex/node_modules/v8flags/index.js:79:12
    at /Users/gideonthomas/publish.webmaker.org/node_modules/knex/node_modules/v8flags/index.js:35:7
    at doNTCallback0 (node.js:407:9)
    at process._tickCallback (node.js:336:13)
    at Function.Module.runMain (module.js:477:11)
    at startup (node.js:117:18)
    at node.js:951:3

npm ERR! Darwin 14.0.0
npm ERR! argv "/usr/local/Cellar/nvm/0.25.4/versions/node/v4.1.1/bin/node" "/usr/local/opt/nvm/versions/node/v4.1.1/bin/npm" "run" "seed"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.4
npm ERR! code ELIFECYCLE
npm ERR! publish.webmaker.org@0.0.1 seed: `knex seed:run`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the publish.webmaker.org@0.0.1 seed script 'knex seed:run'.
npm ERR! This is most likely a problem with the publish.webmaker.org package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     knex seed:run
npm ERR! You can get their info via:
npm ERR!     npm owner ls publish.webmaker.org
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/gideonthomas/publish.webmaker.org/npm-debug.log

npm ERR! Darwin 14.0.0
npm ERR! argv "/usr/local/Cellar/nvm/0.25.4/versions/node/v4.1.1/bin/node" "/usr/local/opt/nvm/versions/node/v4.1.1/bin/npm" "run" "knex"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.4
npm ERR! code ELIFECYCLE
npm ERR! publish.webmaker.org@0.0.1 knex: `npm run migrate && npm run seed`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the publish.webmaker.org@0.0.1 knex script 'npm run migrate && npm run seed'.
npm ERR! This is most likely a problem with the publish.webmaker.org package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run migrate && npm run seed
npm ERR! You can get their info via:
npm ERR!     npm owner ls publish.webmaker.org
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/gideonthomas/publish.webmaker.org/npm-debug.log
```

To fix this, I had to run the following everytime I wanted to run `npm run knex`:
```
dropdb publish
createdb publish
npm run knex
```

This should be documented or the process made better.

cc @Pomax, @ashleygwilliams, @sedge

**Comment by Pomax** [comment]
The knex task is no longer allowed to wipe the database, since it's too easy to accidentally delete data from the production database. I'll file a PR with the docs update for the readme.
