### ISSUE TITLE
Bluebird throws rouge promise warning

### ISSUE THREAD

**Issue by ryanwarsaw** [mozilla/publish.webmaker.org#267]
I was digging through the `publish.webmaker.org` code to see if I could identify what might be causing some of the downtime issues we've been having today, and I saw this:

```	
6:58 PM
(node:75811) Warning: a promise was created in a handler at domain.js:293:12 but was not returned from it, see http://goo.gl/rRqMUw
    at Function.Promise.cast (/Users/ryanwarsaw/Development/Mozilla/publish.webmaker.org/node_modules/bluebird/js/release/promise.js:196:13)
    at FilesController.update (/Users/ryanwarsaw/Development/Mozilla/publish.webmaker.org/api/classes/base_controller.js:144:28)```

Originally Bluebird didn't give me the file that was the origin of the error, so I had to append some verbose code to the Bluebird dependency in order to identify that last line. This might just be a harmless issue, I didn't have enough time to look into it to figure that out.

cc: @gideonthomas

**Comment by gideonthomas** [comment]
Sorry for getting to this so late. I'm pretty sure this is a harmless error that bluebird is throwing. Hapi passes a callback called `reply` into our handlers. This callback usually expects a promise chain to be passed in. We create this promise chain in the handler and pass it into the `reply` callback and since we don't return it (sometimes we do, but it doesn't change anything), bluebird warns us about a promise that hasn't been returned from a function.

On the other hand, the number of connections to the db does not tally with the number of users that are using thimble at a given point of time. I wonder if maybe this might be related to that somehow. I don't really know, but I will take a look and try to dig up what's happening.
