### ISSUE TITLE
error on `node app`

### ISSUE THREAD

**Issue by ashleygwilliams** [mozilla/publish.webmaker.org#8]
after following the instructions in the `README` i get an error on `node app`. 

seems like there needs to be a `rename.js` in the `./routes/project/` directory and there isn't.

details:
```
(jessie)ag_dubs@localhost:~/Mozilla/publish.webmaker.org$ node app 

module.js:340
    throw err;
          ^
Error: Cannot find module './project/rename.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.exports.register (/home/ag_dubs/Mozilla/publish.webmaker.org/routes/index.js:16:3)
    at /home/ag_dubs/Mozilla/publish.webmaker.org/node_modules/hapi/lib/plugin.js:254:14
    at iterate (/home/ag_dubs/Mozilla/publish.webmaker.org/node_modules/hapi/node_modules/items/lib/index.js:35:13)
    at done (/home/ag_dubs/Mozilla/publish.webmaker.org/node_modules/hapi/node_modules/items/lib/index.js:27:25)
    at Object.exports.register (/home/ag_dubs/Mozilla/publish.webmaker.org/authentication/index.js:11:3)
    at /home/ag_dubs/Mozilla/publish.webmaker.org/node_modules/hapi/lib/plugin.js:254:14
```

**Comment by ashleygwilliams** [comment]
looks like the idea is to handle `rename` here: https://github.com/mozilla/publish.webmaker.org/blob/19fa9f22d16ca8c647b1397b464fd8b0366d8e78/routes/file/create-update.js

**Comment by gideonthomas** [comment]
yeah sorry, https://github.com/mozilla/publish.webmaker.org/pull/6 fixes that
